plan:
	AWS_PROFILE=realm-europe-prod go run *.go -services aws-service-plans.json

apply:
	AWS_PROFILE=realm-europe-prod go run *.go -services aws-service-plans.json apply

report:
	AWS_PROFILE=realm-europe-prod go run *.go -services aws-service-plans.json report